create table user_Table (
    id int8 generated by default as identity primary key,
    username varchar(40),
    password varchar(100),
    email varchar(60)
);

drop table user_Table;

drop table role;

drop table user_roles;

drop table movies;

create table role (
    role_Name varchar(20) primary key
);

create table user_roles (
    id int8 references user_Table,
    role_Name varchar references role
);

create table movies (
    id int8 generated by default as identity primary key,
    movie_Name varchar(50),
    release_Date date,
    earnings float8,
    currency varchar references currencies
);

create table currencies (
    currency varchar(10) primary key
);

create table actors (
    id int8 generated by default as identity primary key,
    firstname varchar(50),
    lastname varchar(50),
    birthday date
)