create table userTable (
    id int8 generated by default as identity primary key,
    username varchar(40),
    password varchar(100),
    email varchar(60)
);

drop table userTable;

drop table role;

create table role (
    roleName varchar(20) primary key
);

create table roles (
    id int8 references userTable,
    roleName varchar references role
);

create table movies (
    id int8 generated by default as identity primary key,
    movieName varchar(50),
    releaseDate date,
    earnings float8,
    currency varchar references currencies
);

create table currencies (
    currency varchar(10) primary key
);

create table actors (
    id int8 generated by default as identity primary key,
    firstName varchar(50),
    secondName varchar(50),
    birthday date
)